apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configuration-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: configuration-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: configuration-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  # mountOptions:
  #     - dir_mode=0777
  #     - file_mode=0777
  #     - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-pv
    volumeAttributes:
      source: \\10.0.2.4\Data # replace with private IP from VNET
    nodeStageSecretRef:
      name: smb-secret
      namespace: apps